name: 'Build docker stage'
description: 'Reusable action for building and pushing docker stages'

inputs:
  target:
    description: 'Docker build target stage'
    required: true
  file:
    description: 'Path to Dockerfile'
    required: true
  host:
    description: 'Build host'
    required: true
  build-args:
    description: 'Build arguments'
    required: false
    default: ''
  secrets:
    description: 'Build secrets'
    required: false
    default: ''
  tags:
    description: 'Image tags'
    required: true
  push:
    description: 'Whether to push the image to registry'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Log in to Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: dakkshesh07
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        target: ${{ inputs.target }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ghcr.io/clangbuiltarduino/llvm-${{ inputs.host }}-${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}