name: AVR bfd Build Pipeline

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build bfd linker for avr
        uses: docker/build-push-action@v6
        with:
          context: .
          target: packing
          file: dockerfiles/bfd/avr-linux-amd64.Dockerfile
          push: false
          tags: ghcr.io/clangbuiltarduino/avr-bfd-amd64-linux:${{ github.sha }}
          secrets: |
            "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}"