name: LLVM Build Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG_NAME: clangbuiltarduino
  REPO_NAME: tc-build
  IMAGE_NAME: llvm-linux

jobs:
  deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: dakkshesh07
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build deps stage
        uses: docker/build-push-action@v5
        with:
          context: .
          target: deps-local
          file: dockerfiles/linux/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}-deps:${{ github.sha }}

  stage1:
    needs: deps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: dakkshesh07
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build stage1
        uses: docker/build-push-action@v5
        with:
          context: .
          target: stage1-local
          file: dockerfiles/linux/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}-stage1:${{ github.sha }}
          build-args: |
            BUILD_TYPE=remote
            DEPS_IMAGE=${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}-deps:${{ github.sha }}

  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: dakkshesh07
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build stage2
        uses: docker/build-push-action@v5
        with:
          context: .
          target: stage2-local
          file: dockerfiles/linux/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}-stage2:${{ github.sha }}
          build-args: |
            BUILD_TYPE=remote
            STAGE1_IMAGE=${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}-stage1:${{ github.sha }}

  extra_postbuild:
    needs: stage2
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: dakkshesh07
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build extras and post build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: extrabuild
          file: dockerfiles/linux/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            BUILD_TYPE=remote
            STAGE2_IMAGE=${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}-stage2:${{ github.sha }}
          secrets: |
            "GH_TOKEN=${{ secrets.GH_TOKEN }}"
