name: LLVM Build Pipeline

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG_NAME: clangbuiltarduino
  IMAGE_NAME: llvm-linux

jobs:
  deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build deps stage
        uses: ./.github/actions/stage-builder
        with:
          target: deps-local
          host: linux
          file: dockerfiles/linux/Dockerfile
          push: true
          tags: deps:${{ github.sha }}

  stage1:
    needs: deps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
          
      - name: Build stage1
        uses: ./.github/actions/stage-builder
        with:
          target: stage1-local
          host: linux
          file: dockerfiles/linux/Dockerfile
          push: true
          tags: stage1:${{ github.sha }}
          build-args: |
            BUILD_TYPE=remote
            DEPS_IMAGE=ghcr.io/clangbuiltarduino/llvm-linux-deps:${{ github.sha }}

  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
          
      - name: Build stage2
        uses: ./.github/actions/stage-builder
        with:
          target: stage2-local
          host: linux
          file: dockerfiles/linux/Dockerfile
          push: true
          tags: stage2:${{ github.sha }}
          build-args: |
            BUILD_TYPE=remote
            STAGE1_IMAGE=ghcr.io/clangbuiltarduino/llvm-linux-stage1:${{ github.sha }}

  extra_postbuild:
    needs: stage2
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
          
      - name: Build extras and post build
        uses: ./.github/actions/stage-builder
        with:
          target: extrabuild
          host: linux
          file: dockerfiles/linux/Dockerfile
          push: false
          tags: extrabuild:${{ github.sha }}
          build-args: |
            BUILD_TYPE=remote
            STAGE2_IMAGE=ghcr.io/clangbuiltarduino/llvm-linux-stage2:${{ github.sha }}
          secrets: |
            "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}"
