name: AVR sysroot Build Pipeline

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG_NAME: clangbuiltarduino
  IMAGE_NAME: sysroot-avr

jobs:
  build-avr-sysroot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build avr sysroot
        uses: ./.github/actions/sysroot-builder
        with:
          target: avr
          push: true
          sha: ${{ github.sha }}
          secrets: |
            "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          token: ${{ secrets.GITHUB_TOKEN }}