name: AVR sysroot Build Pipeline

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build avr sysroot
        uses: ./.github/actions/sysroot-builder
        with:
          target: avr
          push: false
          sha: ${{ github.sha }}
          secrets: |
            "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          token: ${{ secrets.GITHUB_TOKEN }}